id: AC14C8934
title: 'The Swift Bestowal of Blessings: A Prayer to the Glorious Protector Guru'
type: translation
pechas:
- IBB8A8942
- IF8A3FE0F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:50.717557
  last_modified_at: 2023-01-04 11:38:50.717567
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IBB8A8942/7857: '6545'
  IF8A3FE0F/6E4F: '6545'
